### ISSUE TITLE
mUSDT does not update

### ISSUE THREAD

**Issue by Redoudou** [Jovells/zksync-web3js-paymaster-demo#2] opened 2024-09-27 21:04 UTC
The value on my mUSDT does not update on the vercel page 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/14d2110a-685c-4fd5-892c-34289619d08a">
https://web3js-zksync-plugin.vercel.app/

while in my wallet I have much more 
<img width="331" alt="image" src="https://github.com/user-attachments/assets/79cfc212-454f-4396-9c73-df379286f58c">

Edit it is actually because I am connected with another account than the one I am showing in my metamask. 
<img width="327" alt="image" src="https://github.com/user-attachments/assets/a6bbc74c-3ca8-4e4c-815d-4ebc3439c016">

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/74e30761-3123-48d8-aba0-fabfbbd2da9e">

**Comment by Jovells** [comment] 2024-09-27 21:31
I just just took a look at at and it works fine at my end. i am unable to reproduce the issue. Could you try again?

**Comment by Jovells** [comment] 2024-09-27 21:33
I just saw the edit. Guess I can close this issue now

**Closed as completed** 2024-09-27 21:34 UTC
